###############################################################################
# Find DAQ USB3-FRM13-B SDK
#
#     find_package(DAQUSB3FRM13BSDK)
#
# Variables defined by this module:
#
#  DAQUSB3FRM13BSDK_FOUND                 True if DAQ USB3-FRM13-B SDK found
#  DAQUSB3FRM13B_SDK_VERSION              The version of DAQ USB3-FRM13-B SDK
#  DAQUSB3FRM13B_SDK_INCLUDE_DIR          The location(s) of DAQ USB3-FRM13-B SDK headers
#  DAQUSB3FRM13B_SDK_LIBRARY_DIR          Libraries needed to use DAQ USB3-FRM13-B SDK
#  DAQUSB3FRM13B_SDK_BINARY_DIR           Binaries needed to use DAQ USB3-FRM13-B SDK

SET(DAQUSB3FRM13B_SDK_PATH_HINTS
  "../ThirdParty/DAQUSB3FRM13B"
  "../Plus-bin/DAQUSB3FRM13B"
  
  )

find_path(DAQUSB3FRM13B_SDK_DIR include/usb3_frm13_import.h
  PATHS ${DAQUSB3FRM13B_SDK_PATH_HINTS}
  DOC "DAQ USB3-FRM13-B SDK directory")

if (DAQUSB3FRM13B_SDK_DIR)
  # Include directories
  set(DAQUSB3FRM13B_SDK_INCLUDE_DIR ${DAQUSB3FRM13B_SDK_DIR}/include)
  mark_as_advanced(DAQUSB3FRM13B_SDK_INCLUDE_DIR)

  # Libraries
  SET(PLATFORM_SUFFIX "")

  IF (CMAKE_HOST_WIN32 AND CMAKE_CL_64 )
    SET(PLATFORM_SUFFIX "x64")
    SET(SDK_FILENAME "USB3-FRM13_x64.dll")
	SET(LIB_FILENAME "USB3-FRM13_x64.lib")
  ENDIF (CMAKE_HOST_WIN32 AND CMAKE_CL_64 )

  IF (CMAKE_HOST_WIN32 AND NOT CMAKE_CL_64 )
    SET(PLATFORM_SUFFIX "x86")
	SET(SDK_FILENAME "USB3-FRM13.dll")
	SET(LIB_FILENAME "USB3-FRM13.lib")
  ENDIF (CMAKE_HOST_WIN32 AND NOT CMAKE_CL_64 )

  find_library(DAQUSB3FRM13B_SDK_LIBRARY
            NAMES ${LIB_FILENAME}
            PATHS "${DAQUSB3FRM13B_SDK_DIR}/bin/${PLATFORM_SUFFIX}/" NO_DEFAULT_PATH
            PATH_SUFFIXES ${PLATFORM_SUFFIX})

  find_path(DAQUSB3FRM13B_SDK_BINARY
            NAMES ${SDK_FILENAME}
            PATHS "${DAQUSB3FRM13B_SDK_DIR}/bin/${PLATFORM_SUFFIX}/" NO_DEFAULT_PATH
            PATH_SUFFIXES ${PLATFORM_SUFFIX})

 
  mark_as_advanced(DAQUSB3FRM13B_SDK_LIBRARY)
  mark_as_advanced(DAQUSB3FRM13B_SDK_BINARY)

  set(DAQUSB3FRM13B_BIN_FILE ${DAQUSB3FRM13B_SDK_BINARY} "/" ${SDK_FILENAME})

  set(DAQUSB3FRM13B_SDK_VERSION "1.0")

endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(DAQUSB3FRM13BSDK
  FOUND_VAR DAQUSB3FRM13BSDK_FOUND
  REQUIRED_VARS DAQUSB3FRM13B_SDK_DIR DAQUSB3FRM13B_SDK_BINARY DAQUSB3FRM13B_SDK_LIBRARY DAQUSB3FRM13B_SDK_INCLUDE_DIR
  VERSION_VAR DAQUSB3FRM13B_SDK_VERSION
)
